version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - volumenDocker:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      
  drupal:
    image: drupal
    ports:
      - "81:80"
    volumes:
      - volumenDocker:/var/www/html
    depends_on:
      - db
    restart: always
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_PORT: "3306"
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: root
      DRUPAL_DB_PASSWORD: example
volumes:
  volumenDocker:

